<?php
function Conectarse()
{
	// include("../consultas/conexion.phtml");
	//if (!($link=mysql_connect("localhost","root","12345")))
	if (!($link=mysql_connect("localhost","root","")))
	{
		echo "Error conectando a la base de datos.";
		exit();
	}
	if (!mysql_select_db("lavadero",$link))
	{
		echo "Error seleccionando la base de datos.";
		exit();
	}
	return $link;
}

$link=Conectarse();
/*echo "Conexión con la base de datos conseguida.<br>";*/

mysql_close($link); //cierra la conexion
?>